package com.kt.ibs.entity;

public enum AuditType {
    LOGIN,
    LOGIN_FAILURE,
    ACCOUNT_LOCKED,
    ACCOUNTS_LIST,
    BEN_APPR_SUCCESS,
    BEN_APPR_FAIL,
    BEN_INITIATED,
    CUSTOMER_REGISTRATION_INITIATED,
    CUSTOMER_REGISTRATION_SUCCESS,
    CUSTOMER_REGISTRATION_FAILED,
    TRANSFER_INITIATED,
    TRANSFER_APPROVAL_SUCCESS,
    TRANSFER_FAILED_T24_ERROR,
    TRANSFER_APPROVAL_FAILED,
    CORE_BEN_PAYMENT_SUCCESS;

}
